### ISSUE TITLE
Recommendation scene structure causes problems

### ISSUE THREAD

**Issue by KCraw** [project-gustave/gustave-client#18]
1. The FAB (Gustave button) needs to be present whenever a recommendation is being displayed, whether short or detail view. According to the MD rules, since its function doesn't change, the FAB should stay on screen during the transition. 

2. A recommendation should always be swipeable to get to the next recommendation, whether we are in short or detail view. A user shouldn't have to nav back to the short view just to swipe right or left. If they are separate routes, then recIndex state must be kept in-sync between routes. There should be a single source of truth.

3. A recommendation should always be swipeable to get to the next recommendation, even if the current recommendation was navigated to directly and not via the recommendations stack. If I navigate through the favorites menu to a recommendation, I should be able to right or left swipe to get to the next recommendation on the recommendations stack (and update favs accordingly).

a. We could have one recommendation scene with a Recommendation component that can expand or contract via subcomponents, as Jim suggested previously.
b. We could have the FAB and recIndex exist higher up the hierarchy; we could either pass in the recIndex and a method to increment it to both components, or we could pass in a single recommendation to both components and a method to increment to the next recommendation.
c. ???

**Comment by KCraw** [comment]
3. A recommendation should always be swipeable to get to the next recommendation, even if the current recommendation was navigated to directly and not via the recommendations stack. If I navigate through the favorites menu to a recommendation, I should be able to right or left swipe to get to the next recommendation on the recommendations stack (and update favs accordingly).

**Comment by KCraw** [comment]
(3) is up for debate. I'm not sure whether that's the most natural interaction, or whether backing up to the favs menu, and then back to the normal recommendations stack is the correct flow. 

But (1) and (2) definitely need to happen.

**Comment by danmconrad** [comment]
I definitely agree with 1 and 2, so maybe we should go back to a toggleable state. Can we differentiate between a recommendation and an event?

I agree on 3 being up for debate. I'm inclined to say it'll be jarring because it interrupts the flow of a set of events that the user can back out of. If we instead indicated to the user that the card in the recommendation**s** scene are swipeable compared to the other representations of a thing to do we may be able to get away with not having the user expect the same interaction.


* Recommendations 
  * Recommendation (can be swiped)
    * Event Summary
    * Event Detail
* Concierge
  * Event Commitment
* Settings
* Favorites
  * Event Preview (not tall, has mini-G button on the right)
    * Event Detail

**Comment by KCraw** [comment]
I could be pretty easily convinced that I'm wrong about 3. 

I think Jim had some great ideas on how to deal with toggleable state for a single recommendation card, and I think a toggleable card is the way to go, IMHO. 

You make a good point about visually indicating to a user that the available interactions are different. We're using cards to visually indicate that an item can be swiped off the screen. What if we rendered essentially the same expandable view, but as a full screen View instead of a Card when it's an individual recommendation and not a stack of recommendations?

**Comment by danmconrad** [comment]
+1 on the full width/height card when in the recommendation view coming from the favorites list or anything other than the recommendations scene.

Possibility for indicating interaction. (not super attached to it):
![one](https://cloud.githubusercontent.com/assets/3791768/13187684/35379c12-d712-11e5-994e-00bbd0006739.png)

**Comment by danmconrad** [comment]
![two](https://cloud.githubusercontent.com/assets/3791768/13188004/5f519078-d714-11e5-9d7c-fba9fd083df7.png)

**Comment by KCraw** [comment]
There's a part of me that like the clean lines of the card floating on the background and I'd like to try that first. 

But one advantage of a visual indicator would be that we could also indicate the character of each directional swipe through either icon or color (or both). So I think we should keep something like this in mind if we find that we need something.

**Comment by KCraw** [comment]
- RecommendationsScene (expects paginated recommendations)
 - Recommendation component (expandable) wrapped in Card
- RecommendationScene (expects single recommendation and optional startView prop)
 - Recommendation component (expandable) wrapped in View 

Recommendation component accepts a startView prop that accepts either 'expanded' or 'collapsed' and defaults to 'collapsed'.

**Comment by jimbol** [comment]
I'm thinking of writing a wrapper component for Recommendations to handle animations. This would allow us to just wrap the card in the detail view in an Animated Recommendation component, giving it the same swipability as the other view.  

I do, though, feel like the animation that runs when you press "more deets" feels like more of a context change than it is supposed to be.  This is due to the fact that the deet view slides over, and covers the Recommendation view.  Perhaps if we can figure out a transition which doesnt change z-index at all.

Craw, that error state you mentioned where we run out of cards is an opportunity to switch approaches.  For example, we could run the same intelligence at a wider radius OR run a food only algorithm OR drinks only.  This is like that filter card I described where the user can swipe one of ~3 options, "Look further away", "Food only", "Drinks only".  Warmer/cooler for each option.  Or they could just be pressable.

I think having an indicator that a Card is swipable is a good idea.  Right now, the only things that are swipable are Cards.  So we could make the rule that if its a card, its swipable, and if its full screen, its not swipable.  Following that line of thought, if we have Recommendation or detail views that we dont want to allow swiping on (like in the saved list maybe), they could be full screen instead of cards.

**Comment by KCraw** [comment]
I think where Conrad and I were heading mentally was having a single Recommendation component that could be interacted with to expand or collapse the level of detail. So there'd be a single component with a toggleable state with transition animations, rather than a separate route/component like there is now.

**Comment by KCraw** [comment]
> Craw, that error state you mentioned where we run out of cards is an opportunity to switch approaches. For example, we could run the same intelligence at a wider radius OR run a food only algorithm OR drinks only. This is like that filter card I described where the user can swipe one of ~3 options, "Look further away", "Food only", "Drinks only". Warmer/cooler for each option. Or they could just be pressable.

I think this is a really good idea and will work 99.99% of the time. We'll still need to handle the case where we simply don't have any suggestions; e.g., somebody travels to a small town where we don't have any events in the database to recommend, or maybe there's only 3 things and Gustave predicts you'd hate all of them. It's totally an edge case, but one we need to handle even if we have a great strategy for trying to avoid ever running into it. 

I think your suggestion is a great strategy for avoiding it.

**Comment by jimbol** [comment]
Yea I agree with the single Recommendation component direction.  I was stating that the wrapper I'm writing should work for both.

We should maintain a list of possible error states, I sent one out.
